2019-08-07 20:18:32,397 ERROR 45640 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45640
hostname: DESKTOP-DUAKF8G

2019-08-07 20:23:03,728 ERROR 45640 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45640
hostname: DESKTOP-DUAKF8G

2019-08-07 20:24:29,729 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:26:27,753 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:26:51,793 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:27:10,917 ERROR 56200 [-/127.0.0.1/-/8ms GET /api/user] nodejs.ReferenceError: service is not defined
    at UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\user.js:6:18)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 56200
hostname: DESKTOP-DUAKF8G

2019-08-07 20:32:05,304 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:32:18,090 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:36:33,940 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:41:40,311 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:43:37,576 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:48:25,184 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:48:29,662 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:49:59,250 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:50:08,515 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:51:24,178 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:52:40,461 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:52:47,660 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:05,363 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:08,149 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:10,875 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:13,392 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:28,964 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:46,469 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:53:49,580 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:55:59,756 ERROR 37308 nodejs.ServerNoResponseError: server 127.0.0.1:64391 no response in 40000ms, maybe the socket is end on the other side. (address: 127.0.0.1:64391)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ServerNoResponseError"
pid: 37308
hostname: DESKTOP-DUAKF8G

2019-08-07 20:57:26,959 ERROR 18964 nodejs.ClusterClientNoResponseError: client no response in 147202ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 20:58:29,518 ERROR 18964 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 18964
hostname: DESKTOP-DUAKF8G

2019-08-07 21:28:20,595 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:28:58,842 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:29:01,866 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:35:52,375 ERROR 43580 [-/127.0.0.1/-/8ms GET /api/role/getResource] nodejs.ReferenceError: result is not defined
    at RoleService.getResource (C:\vipdata\vipproject\2019projects\cms-api\app\service\role.js:44:5)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

pid: 43580
hostname: DESKTOP-DUAKF8G

2019-08-07 21:42:17,962 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:42:51,702 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:44:06,147 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:45:02,355 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:47:07,505 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:47:49,031 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:49:32,539 ERROR 348 [-/127.0.0.1/-/7ms GET /api/user?pageNum=2&pageSize=3] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'age' in 'order clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` ORDER BY `id` DESC, `age` ASC LIMIT 3, 3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'age' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` ORDER BY `id` DESC, `age` ASC LIMIT 3, 3"
name: "ER_BAD_FIELD_ERRORError"
pid: 348
hostname: DESKTOP-DUAKF8G

2019-08-07 21:49:59,018 ERROR 51420 [-/127.0.0.1/-/17ms GET /api/user?pageNum=2&pageSize=3] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `user` WHERE `where` = 
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT COUNT(*) as count FROM `user` WHERE `where` = "
name: "ER_PARSE_ERRORError"
pid: 51420
hostname: DESKTOP-DUAKF8G

2019-08-07 21:50:47,430 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:50:50,222 ERROR 52808 [-/127.0.0.1/-/14ms GET /api/user?pageNum=2&pageSize=3&1=1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column '1' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `1` = '1' ORDER BY `id` DESC, `email` ASC LIMIT 3, 3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '1' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `1` = '1' ORDER BY `id` DESC, `email` ASC LIMIT 3, 3"
name: "ER_BAD_FIELD_ERRORError"
pid: 52808
hostname: DESKTOP-DUAKF8G

2019-08-07 21:51:41,725 ERROR 54252 [-/127.0.0.1/-/20ms GET /api/user?pageNum=2&pageSize=3&1=1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column '1' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `1` = '1' ORDER BY `id` DESC LIMIT 3, 3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '1' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `1` = '1' ORDER BY `id` DESC LIMIT 3, 3"
name: "ER_BAD_FIELD_ERRORError"
pid: 54252
hostname: DESKTOP-DUAKF8G

2019-08-07 21:52:40,629 ERROR 58912 [-/127.0.0.1/-/21ms GET /api/user?pageNum=2&pageSize=3&username=zhangsan] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'"
name: "ER_BAD_FIELD_ERRORError"
pid: 58912
hostname: DESKTOP-DUAKF8G

2019-08-07 21:53:57,111 ERROR 58912 [-/127.0.0.1/-/3679ms GET /api/user?pageNum=2&pageSize=3&username=zhangsan] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'"
name: "ER_BAD_FIELD_ERRORError"
pid: 58912
hostname: DESKTOP-DUAKF8G

2019-08-07 21:54:25,729 ERROR 21552 [-/127.0.0.1/-/18ms GET /api/user?pageNum=2&pageSize=3&username=zhangsan] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'"
name: "ER_BAD_FIELD_ERRORError"
pid: 21552
hostname: DESKTOP-DUAKF8G

2019-08-07 21:54:37,760 ERROR 33648 [-/127.0.0.1/-/11ms GET /api/user?pageNum=2&pageSize=3&username=zhangsan] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'"
name: "ER_BAD_FIELD_ERRORError"
pid: 33648
hostname: DESKTOP-DUAKF8G

2019-08-07 21:55:07,876 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:55:11,780 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:55:12,136 ERROR 45712 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 45712
hostname: DESKTOP-DUAKF8G

2019-08-07 21:55:32,357 ERROR 56908 [-/127.0.0.1/-/25ms GET /api/user?pageNum=2&pageSize=3&username=zhangsan] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT COUNT(*) as count FROM `user` WHERE `where` = `username` = 'zhangsan'"
name: "ER_BAD_FIELD_ERRORError"
pid: 56908
hostname: DESKTOP-DUAKF8G

2019-08-07 21:56:22,546 ERROR 50664 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 50664
hostname: DESKTOP-DUAKF8G

2019-08-07 22:04:36,522 ERROR 30524 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 30524
hostname: DESKTOP-DUAKF8G

2019-08-07 22:08:50,635 ERROR 30524 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 30524
hostname: DESKTOP-DUAKF8G

2019-08-07 22:09:02,130 ERROR 30524 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:139:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 30524
hostname: DESKTOP-DUAKF8G

2019-08-18 10:31:40,793 ERROR 16064 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 16064
hostname: DESKTOP-DUAKF8G

2019-08-18 10:31:43,146 ERROR 16064 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 16064
hostname: DESKTOP-DUAKF8G

2019-08-18 10:31:43,151 ERROR 16064 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 16064
hostname: DESKTOP-DUAKF8G

2019-08-18 10:33:44,673 ERROR 20108 [-/127.0.0.1/-/30ms POST /api/signin] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'prefix' in 'where clause'
    at Query.Sequence._packetToError (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_mysql@2.17.1@mysql\lib\Pool.js:199:23)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `username` = '2' AND `password` = '222' AND `prefix` = '086' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'prefix' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `username` = '2' AND `password` = '222' AND `prefix` = '086' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 20108
hostname: DESKTOP-DUAKF8G

2019-08-18 10:40:08,214 ERROR 2888 nodejs.ServerNoResponseError: server 127.0.0.1:54075 no response in 39999ms, maybe the socket is end on the other side. (address: 127.0.0.1:54075)
    at Timeout._onTimeout (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ServerNoResponseError"
pid: 2888
hostname: DESKTOP-DUAKF8G

2019-08-18 10:50:27,986 ERROR 13636 nodejs.ClusterClientNoResponseError: client no response in 679770ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 10:58:11,896 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 10:58:54,898 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 10:58:59,112 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 10:59:27,575 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 10:59:30,967 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 11:00:05,161 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 11:01:22,121 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 11:01:27,594 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 11:01:33,445 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 11:02:26,011 ERROR 13636 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13636
hostname: DESKTOP-DUAKF8G

2019-08-18 12:17:49,219 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 12:20:37,444 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 12:22:16,237 ERROR 7868 nodejs.ServerNoResponseError: server 127.0.0.1:59356 no response in 20001ms, maybe the socket is end on the other side. (address: 127.0.0.1:59356)
    at Timeout._onTimeout (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ServerNoResponseError"
pid: 7868
hostname: DESKTOP-DUAKF8G

2019-08-18 12:55:18,677 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 17:10:39,362 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 17:11:44,886 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 17:13:27,082 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 17:15:21,801 ERROR 12744 [-/127.0.0.1/-/7ms GET /api/user?pageNum=1&username=74] nodejs.ReferenceError: field is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:16:34)
    at UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:45)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 12744
hostname: DESKTOP-DUAKF8G

2019-08-18 17:15:21,816 ERROR 12744 [-/127.0.0.1/-/2ms GET /api/user?pageNum=1&username=4] nodejs.ReferenceError: field is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:16:34)
    at UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:45)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 12744
hostname: DESKTOP-DUAKF8G

2019-08-18 17:15:21,820 ERROR 12744 [-/127.0.0.1/-/0ms GET /api/user?pageNum=1&username=4] nodejs.ReferenceError: field is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:16:34)
    at UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:45)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-core@4.17.3@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\vipdata\vipproject\2019projects\cms-api\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 12744
hostname: DESKTOP-DUAKF8G

2019-08-18 17:15:57,568 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2019-08-18 17:18:12,906 ERROR 29480 [-/127.0.0.1/-/18ms GET /api/user?pageNum=1&username=4] nodejs.ReferenceError: total is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:26:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:18)
    at async C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-development@2.4.3@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-session@5.12.2@koa-session\index.js:41:7)
    at async bodyParser (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-bodyparser@4.2.1@koa-bodyparser\index.js:86:5)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29480
hostname: DESKTOP-DUAKF8G

2019-08-18 17:19:05,461 ERROR 29480 nodejs.ServerNoResponseError: server 127.0.0.1:59356 no response in 20003ms, maybe the socket is end on the other side. (address: 127.0.0.1:59356)
    at Timeout._onTimeout (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ServerNoResponseError"
pid: 29480
hostname: DESKTOP-DUAKF8G

2019-08-18 17:19:05,497 ERROR 29480 [-/127.0.0.1/-/21074ms GET /api/user?pageNum=1&username=4] nodejs.ReferenceError: total is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:26:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:18)
    at async C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-development@2.4.3@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-session@5.12.2@koa-session\index.js:41:7)
    at async bodyParser (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-bodyparser@4.2.1@koa-bodyparser\index.js:86:5)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29480
hostname: DESKTOP-DUAKF8G

2019-08-18 17:19:05,518 ERROR 29480 [-/127.0.0.1/-/12ms GET /api/user?pageNum=1&username=4] nodejs.ReferenceError: total is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:26:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:18)
    at async C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-development@2.4.3@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-session@5.12.2@koa-session\index.js:41:7)
    at async bodyParser (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-bodyparser@4.2.1@koa-bodyparser\index.js:86:5)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29480
hostname: DESKTOP-DUAKF8G

2019-08-18 17:19:05,540 ERROR 29480 [-/127.0.0.1/-/61ms GET /api/user?pageNum=1&=] nodejs.ReferenceError: total is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:26:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:18)
    at async C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-development@2.4.3@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-session@5.12.2@koa-session\index.js:41:7)
    at async bodyParser (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-bodyparser@4.2.1@koa-bodyparser\index.js:86:5)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29480
hostname: DESKTOP-DUAKF8G

2019-08-18 17:19:05,554 ERROR 29480 [-/127.0.0.1/-/11ms GET /api/user?pageNum=1&=] nodejs.ReferenceError: total is not defined
    at UserService.select (C:\vipdata\vipproject\2019projects\cms-api\app\service\base.js:26:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async UserController.index (C:\vipdata\vipproject\2019projects\cms-api\app\controller\base.js:16:18)
    at async C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-development@2.4.3@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_egg-security@2.6.1@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-session@5.12.2@koa-session\index.js:41:7)
    at async bodyParser (C:\vipdata\vipproject\2019projects\cms-api\node_modules\_koa-bodyparser@4.2.1@koa-bodyparser\index.js:86:5)
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29480
hostname: DESKTOP-DUAKF8G

2019-08-18 17:55:27,246 ERROR 23112 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 23112
hostname: DESKTOP-DUAKF8G

2023-05-24 13:35:10,716 ERROR 55964 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
    --------------------
    at Protocol._enqueue (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:347:12)
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 55964
hostname: superyangdeMacBook-Pro.local

2023-06-25 09:58:43,266 ERROR 90406 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:347:12)
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 90406
hostname: superyangdeMacBook-Pro.local

2023-06-25 10:05:22,051 ERROR 90755 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'cms'
    at Handshake.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:347:12)
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'cms'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 90755
hostname: superyangdeMacBook-Pro.local

2023-06-25 11:00:01,127 ERROR 91261 [-/127.0.0.1/-/7ms GET /api/role/getUser] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'cms-api.user' doesn't exist
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at RDSClient.select (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:89:23)
    at RoleService.getUser (/Users/superyang/Downloads/cms-api/app/service/role.js:33:34)
    at RoleController.getUser (/Users/superyang/Downloads/cms-api/app/controller/role.js:10:37)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    sql: SELECT * FROM `user`
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'cms-api.user' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `user`"
name: "ER_NO_SUCH_TABLEError"
pid: 91261
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:05:34,859 ERROR 91835 nodejs.ClusterClientNoResponseError: client no response in 705111ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 91835
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:11:39,671 ERROR 92934 nodejs.ClusterClientNoResponseError: client no response in 77845ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 92934
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:17:48,538 ERROR 92940 nodejs.EPIPEError: write EPIPE (address: 127.0.0.1:57698)
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:874:11)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at Follower.sendHeartBeat (/Users/superyang/Downloads/cms-api/node_modules/tcp-base/lib/base.js:105:18)
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/tcp-base/lib/base.js:441:12)
    at listOnTimeout (node:internal/timers:559:17)
errno: -32
code: "EPIPE"
syscall: "write"
name: "EPIPEError"
pid: 92940
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:21:19,694 ERROR 92934 nodejs.ClusterClientNoResponseError: client no response in 71141ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 92934
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:24:10,033 ERROR 92940 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:57698
    at Function.waitFor (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/server.js:243:15)
    at async ClusterClient.[ClusterClient#createClient] (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/wrapper/cluster.js:42:7)
    at async ClusterClient.[ClusterClient#init] (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/wrapper/base.js:72:25)

pid: 92940
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:25:28,774 ERROR 92940 [-/127.0.0.1/-/28533ms POST /api/signup] nodejs.TypeError: address.join is not a function
    at UserController.signup (/Users/superyang/Downloads/cms-api/app/controller/user.js:22:24)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:45:18)
    at /Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:44:32)
    at /Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:36:12

pid: 92940
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:26:30,739 ERROR 92940 [-/127.0.0.1/-/13669ms POST /api/signup] nodejs.TypeError: address.join is not a function
    at UserController.signup (/Users/superyang/Downloads/cms-api/app/controller/user.js:22:24)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:45:18)
    at /Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:44:32)
    at /Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:36:12

pid: 92940
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:28:41,788 ERROR 92940 [-/127.0.0.1/-/4258ms POST /api/signup] nodejs.TypeError: address.join is not a function
    at UserController.signup (/Users/superyang/Downloads/cms-api/app/controller/user.js:22:24)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:45:18)
    at /Users/superyang/Downloads/cms-api/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:44:32)
    at /Users/superyang/Downloads/cms-api/node_modules/koa-compose/index.js:36:12

pid: 92940
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:43:19,742 ERROR 92934 nodejs.ClusterClientNoResponseError: client no response in 73567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 92934
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:46:42,769 ERROR 93176 nodejs.EPIPEError: write EPIPE (address: 127.0.0.1:57698)
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:874:11)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at Follower.sendHeartBeat (/Users/superyang/Downloads/cms-api/node_modules/tcp-base/lib/base.js:105:18)
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/tcp-base/lib/base.js:441:12)
    at listOnTimeout (node:internal/timers:559:17)
errno: -32
code: "EPIPE"
syscall: "write"
name: "EPIPEError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:46:58,094 ERROR 93176 [-/undefined/-/15322ms POST /api/signin] nodejs.ECONNRESETError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
errno: -54
code: "ECONNRESET"
syscall: "read"
headerSent: true
name: "ECONNRESETError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:47:09,326 ERROR 93176 nodejs.TcpConnectionTimeoutError: [TCPBase] socket connect timeout (10000ms) (address: 127.0.0.1:57698) (127.0.0.1)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/tcp-base/lib/base.js:408:19)
    at Object.onceWrapper (node:events:627:28)
    at Socket.emit (node:events:513:28)
    at Socket._onTimeout (node:net:526:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "TcpConnectionTimeoutError"
host: "127.0.0.1"
port: 57698
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:47:09,326 ERROR 93176 nodejs.TcpConnectionTimeoutError: [TCPBase] socket connect timeout (10000ms) (address: 127.0.0.1:57698) (127.0.0.1) (127.0.0.1) (127.0.0.1) (127.0.0.1)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/tcp-base/lib/base.js:408:19)
    at Object.onceWrapper (node:events:627:28)
    at Socket.emit (node:events:513:28)
    at Socket._onTimeout (node:net:526:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "TcpConnectionTimeoutError"
host: "127.0.0.1"
port: 57698
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:47:47,108 ERROR 93176 [-/undefined/-/49011ms POST /api/signin] nodejs.ECONNRESETError: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
errno: -54
code: "ECONNRESET"
syscall: "read"
headerSent: true
name: "ECONNRESETError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:47:47,112 ERROR 93176 [-/undefined/-/49015ms POST /api/signin] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (node:events:513:28)
    at Handshake._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:347:12)
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    sql: SELECT * FROM `user` WHERE `username` = 'superyang' AND `password` = '123456' LIMIT 0, 1
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
headerSent: true
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:50:17,899 ERROR 93176 [-/127.0.0.1/-/4ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_user where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_user where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:54:25,979 ERROR 93176 [-/127.0.0.1/-/6ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_user where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_user where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:55:13,286 ERROR 93176 [-/127.0.0.1/-/3ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_user where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_user where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:55:14,168 ERROR 93176 [-/127.0.0.1/-/4ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_user where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_user where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93176
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:55:14,936 ERROR 93443 [-/127.0.0.1/-/14ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93443
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:55:15,287 ERROR 93443 [-/127.0.0.1/-/5ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93443
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:55:15,552 ERROR 93443 [-/127.0.0.1/-/6ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93443
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:55:44,624 ERROR 93461 [-/127.0.0.1/-/14ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93461
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:56:55,131 ERROR 93461 [-/127.0.0.1/-/2ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93461
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:56:56,192 ERROR 93518 [-/127.0.0.1/-/12ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93518
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:56:56,697 ERROR 93518 [-/127.0.0.1/-/4ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93518
hostname: superyangdeMacBook-Pro.local

2023-06-25 13:57:59,826 ERROR 92934 nodejs.ClusterClientNoResponseError: client no response in 64420ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 92934
hostname: superyangdeMacBook-Pro.local

2023-06-25 14:03:58,647 ERROR 93518 [-/127.0.0.1/-/407657ms GET /api/roleResource] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleResourceController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_resource where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93518
hostname: superyangdeMacBook-Pro.local

2023-06-25 14:03:58,661 ERROR 93518 nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:57698
    at Function.waitFor (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/server.js:243:15)
    at async ClusterClient.[ClusterClient#createClient] (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/wrapper/cluster.js:42:7)
    at async ClusterClient.[ClusterClient#init] (/Users/superyang/Downloads/cms-api/node_modules/cluster-client/lib/wrapper/base.js:72:25)

pid: 93518
hostname: superyangdeMacBook-Pro.local

2023-06-25 14:07:04,241 ERROR 93518 [-/127.0.0.1/-/4ms GET /api/roleUser] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'order clause'
    at Query.Sequence._packetToError (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/superyang/Downloads/cms-api/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:347:12)
    at RDSClient._query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/client.js:23:29)
    at RDSClient.query (/Users/superyang/Downloads/cms-api/node_modules/ali-rds/lib/operator.js:43:31)
    at UserService.select (/Users/superyang/Downloads/cms-api/app/service/base.js:19:38)
    at RoleUserController.index (/Users/superyang/Downloads/cms-api/app/controller/base.js:16:45)
    at Object.callFn (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/superyang/Downloads/cms-api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    sql: SELECT * FROM role_user where 1=1   order by id DESC limit 0,3
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM role_user where 1=1   order by id DESC limit 0,3"
name: "ER_BAD_FIELD_ERRORError"
pid: 93518
hostname: superyangdeMacBook-Pro.local

